---
title: "Scientific Images & Geographic Information Systems (GIS)"
---

The workshop will be held __July 14-15__, 2025 in Building 10 at the NIH Campus in Bethesda, MD.

### Instructors

- Neggin Keshavarazian (Princeton University)
- Amy Schuler (Cary Institute of Ecosystem Studies)
- Mariah Kenney (Carnegie Mellon University)
- Kelly Grove (Florida State University)
- Timothy Norris (University of Miami)


### Resources

::: {.callout-note}
Participants are encouraged to review [DCN's CURATE(D) workflow](https://datacurationnetwork.org/outputs/workflows/) before the first session.
:::

- Pre-workshop preparation
   - GIS  
      - Download and install [QGIS](https://qgis.org/en/site/forusers/download.html).  
      - Download the [1_Environment_Setup_Datasets.zip](https://drive.google.com/file/d/1JQF03Ekmpsvv4tICg6ELMISpPKBCZMXk) adapted from [Kramer et al 2019](https://doi.org/10.13020/znag-tn48).  
      - Please see the [01_Environmental_Setup](https://docs.google.com/presentation/d/1X6JF22flHCWMmzyGbCh661tx573O2LYdHC4ig6yZguc) slide deck for more details (through slide 5).  
      - If you feel adventerous, try to open any part of the setup dataset in QGIS.  
   - Scientific Images  
      - Download and install [ImageJ](https://imagej.net/software/fiji/downloads) to be used to manipulate scientific images. Specifically we will use Fiji which is a distribution of ImageJ that includes additional useful plugins.
         - Windows users are recommended to install in the users directory where it will have permissions to update itself.  
         - Mac users - the software may run through Rosetta if you have a newer M-series processor, this can have some performance cost. Alternatively you can download a [java version](https://forum.image.sc/t/fiji-clij-etc-native-on-apple-silicon-arm64-m1/53627/25) which can run natively.  
- [Shared Notes](https://docs.google.com/document/d/1EwEtSuCKFJzTM6ka3q--y8zz0mPL8GGMDLU3CqNk_oI/edit?tab=t.0) for the entire workshop  
- Slides   
   - [General Workshop Information](https://docs.google.com/presentation/d/1PB2Bue3XhVBzDO3nUQY6pUlJjRk4Bkq4RZCtsIu-clE/edit?slide=id.g34b2dc78b5b_0_129#slide=id.g34b2dc78b5b_0_129)  
   - GIS  
      - [01_Environmental Setup](https://docs.google.com/presentation/d/1X6JF22flHCWMmzyGbCh661tx573O2LYdHC4ig6yZguc)  
      - [02_GIS_Introduction](https://docs.google.com/presentation/d/1HpBwxeyFS9VpQ1pNke5RQvk-X3n1NFZDkw7EUJtJCAI)  
      - [03_Ethics_and_GIS_Data](https://docs.google.com/presentation/d/1PZHbiv3YSXpw9aqnn91zot9cErGpRHh28DKH4gSghwU)  
      - [04_Transofrmations](https://docs.google.com/presentation/d/1U2EcCLWHAbNbU1MsIKimqBSvlToA1b-pu2n6Vxymliw)  
      - [05_GIS_Metadata](https://docs.google.com/presentation/d/1mXO2UKkhrdpsVjPJl2U03b1NaXjVjGvRj_328PMqE8Q)  
   - [Scientific Images](https://docs.google.com/presentation/d/1KNA0DLKbanLcohtYAPreSdejAWpAO1Pa_8-_HCFs45c/edit?slide=id.g2a520746ab6_0_2#slide=id.g2a520746ab6_0_2)  
- [GIS Cheatsheet](https://docs.google.com/document/d/16sQsM1abWYi8kbVriZ0Wnkpiyl8SBC9xrEwmT1RPSt0/edit?usp=sharing)  
- Excercise Data Sets  
   Please download and unzip in an easy to find folder on your computer
   - GIS
      - [01_Environment_Setup_Datasets.zip](https://drive.google.com/file/d/1JQF03Ekmpsvv4tICg6ELMISpPKBCZMXk)  
      - [04_Bad_projection.zip](https://drive.google.com/file/d/1qj5qSn0G_mEKBgzo9Uh6tNF259KpUgO1)  
      - [04_GIS_Transformations_Datasets.zip](https://drive.google.com/file/d/1ybdlW5GnR-z92dpgB_rzxPYpDIYWa_bL)  
      - [04_study_area_cover_type.shp.xml](https://drive.google.com/file/d/1064vbrX3OxOTnGcRGi-vmk5GB2tWs3Qd)  
      - [05_GIS_Dataset_No_ReadMe.zip](https://drive.google.com/file/d/1WhEbG3x3TX9yHlXOpKKQXq5caOhn562w)   
   - Scientific Images  
      - [Dataset for 'Multi‑Step Crystallization of Self‑Organized Spiral Eutectics'](https://deepblue.lib.umich.edu/data/concern/data_sets/h415p962w)  
  
### Schedule

::: {.callout-warning}
The workshop schedule is still being developed and may change!
:::


#### Day 1: July 14th

| Time            | Topic                                                   |
| :-------------- | :------------------------------------------------------ |
| 9:00 AM         | Welcome and DCN background and Icebreaker               |
| 9:30 AM         | Introduction to GIS and geospatial Data Types           |
| 10:30 AM        | Break                                                   |
| 10:45 PM        | GIS Data Types (cont) and Ethical Considerations        |
| 12:00 PM        | Lunch                                                   |
| 1:00 PM         | GIS Transformations                                     |
| 1:45 PM         | Break                                                   |
| 2:00 PM         | GIS Metadata                                            |
| 2:45 PM         | Break                                                   |
| 3:00 PM         | GIS Metadata (cont) and Wrap Up                         |
| 4:00 PM         | End of Day 1                                            |
| 6:00 \- 7:30 PM | Dine Arounds\!                                          |

#### Day 2: July 15th

| Time     | Topic                                                  |
| :------- | :----------------------------------------------------- |
| 9:00 AM  | Welcome Back & Icebreaker                              |
| 9:15 AM  | Introduction to Sci Images and Software                |
| 10:30 AM | Break                                                  |
| 10:45 AM | Image Metadata and Transformation                      |
| 12:00 PM | Lunch                                                  |
| 1:00 PM  | Introduce capstone and datasets; brainstorm with teams |
| 2:15 PM  | Break                                                  |
| 2:30 PM  | Capstone share out and Wrap Up                         |
| 3:00 PM  | End                                                    |

