project:
  type: website
  output-dir: docs

website:
  title: "Specialized Data Curation"
  navbar:
    left:
      - href: index.qmd
        text: Schedule
      - href: bibliography.qmd
        text: Bibliography

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



