project:
  type: website
  output-dir: docs

website:
  title: "Specialized Data Curation"
  navbar:
    left:
      - text: Workshops
        menu: 
        - text: Code & Simulation Data
          href: codesim
        - text: Scientific Images & GIS
          href: scimgis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



