---
title: "Specialized Data Curation Workshops @ NIH"
---

As part of the continuation of the IMLS funded project “[Developing Specialized
Data Curation Training to Address Needed Expertise in Focused
Areas](https://datacurationnetwork.org/expanding-curation-training/)”, the Data
Curation Network is partnering with the National Institutes of Health to offer a
series of data curation workshops on specialized topics.

## Schedule

::: {.callout-warning}
The workshop schedule is still being developed and may change!
:::

### Code & Simulation Data

- Date: May 12-13, 2025  
- Location: NIH Campus (Bethesda, MD)
- Instructors: Seth Erickson and Greg Janée (Code); Wanda Marsolek and L. Wynholds (Simulation Data)

#### Day 1: May 12th

| Time            | Topic                                                   |
| :-------------- | :------------------------------------------------------ |
| 9:00 AM         | Welcome and DCN background and Icebreaker (w/breakfast) |
| 9:30 AM         | Computing platforms and programing languages            |
| 10:30 AM        | Break                                                   |
| 10:45 PM        | Dependencies and Documentation                          |
| 12:00 PM        | Lunch                                                   |
| 1:00 PM         | Licensing and project structure                         |
| 2:30 PM         | Break                                                   |
| 3:00 PM         | Simulation Data Introduction                            |
| 4:00 PM         | End of Day 1                                            |
| 6:00 \- 7:30 PM | Dine Arounds\!                                          |

#### Day 2: May 13th

| Time     | Topic                                                  |
| :------- | :----------------------------------------------------- |
| 9:00 AM  | Welcome Back & Recap from Day 1                        |
| 9:15 AM  | Simulation Data examples and activities                |
| 10:30 AM | Break                                                  |
| 10:45 AM | Simulation Data examples and activities                |
| 12:00 PM | Lunch                                                  |
| 1:00 PM  | Introduce capstone and datasets; brainstrom with teams |
| 2:00 PM  | Capstone share out                                     |
| 2:30 PM  | Workshop wrap up                                       |
| 3:00 PM  | End                                                    |

