---
title: "Code & Simulation Data"
---


::: {.callout-note}
Materials from this workshop are archived in the University of Minnesota's Digital Conservancy: [doi.org/10.24926/2025.276529](https://doi.org/10.24926/2025.276529).
:::

The workshop was held __May 12-13__, 2025 in Building 49 at the NIH Campus in Bethesda, MD.

### Instructors

- Seth Erickson (University of California, Santa Barbara)
- Greg Janée (University of California, Santa Barbara)
- Wanda Marsolek (University of Minnesota)
- L. Wynholds (University of Utah)


### Resources


- [Code Slides](https://conservancy.umn.edu/bitstreams/b6dbdb67-09f6-4cc6-996e-ae74fd6dde63/download)
- [Simulation Slides](https://conservancy.umn.edu/bitstreams/22b4f5cb-d401-4394-bddb-c0b282e16758/download)
- [Virtual Workspace Instructions](workspace.qmd)
- [References](references.qmd)
- [Code Checklist](code_checklist.md)

### Schedule

#### Day 1: May 12th

| Time     | Topic                                        |
| :------- | :------------------------------------------- |
| 9:00 AM  | Welcome and DCN background and Icebreaker    |
| 9:30 AM  | Code: Introduction and Overview              |
| 9:45 AM  | Computing platforms and programing languages |
| 10:45 AM | Break                                        |
| 11:00 PM | Dependencies and Documentation               |
| 12:00 PM | Lunch                                        |
| 1:00 PM  | Licensing and project structure              |
| 2:30 PM  | Capstone Introduction                        |
| 2:45 PM  | Break                                        |
| 3:00 PM  | Simulation Data Introduction and Overview    |
| 4:00 PM  | End of Day 1                                 |
| 6:00 PM  | Dine Arounds\!                               |

#### Day 2: May 13th

| Time     | Topic                                            |
| :------- | :----------------------------------------------- |
| 9:00 AM  | Welcome Back & Recap from Day 1                  |
| 9:15 AM  | Introducing simulation datasets and key features |
| 9:50 AM  | Break                                            |
| 10:05 AM | Metadata and ethical considerations              |
| 10:50 AM | Break                                            |
| 11:00 AM | Data appraisal and transformations               |
| 12:00 PM | Lunch                                            |
| 1:00 PM  | Capstone work time: brainstorm with teams        |
| 2:00 PM  | Capstone share out                               |
| 2:30 PM  | Workshop wrap up                                 |
| 3:00 PM  | End                                              |


### Suggested Citation

Janée, Greg; Erickson, Seth; Wynholds, L.; Marsolek, Wanda. (2025). DCN-NIH Specialized Curation for Code and Simulations Workshop, 2025. Retrieved from the University Digital Conservancy, [https://doi.org/10.24926/2025.276529]().