---
title: "Code & Simulation Data References"
bibliography: references.bib
link-citations: true
nocite: '@*'
---


### Code & Simulation Datasets 

The following resources are used in workshop examples or exercises.

<div class="hanging-indent csl-entry">
Adeodu, O., Gee, M., Mahmoudi, B., Vadigepalli, R., & Kothare, M. 2024. "Simulation of the short term impact of atrial fibrillation on hemodynamic variables (Version 1) [Dataset]". SPARC Portal. DOI: [https://doi.org/10.26275/B0LJ-XSTO](https://doi.org/10.26275/B0LJ-XSTO)
</div>

<div class="hanging-indent csl-entry">
Azzolin, L., Eichenlaub, M., Nagel, C., Nairn, D., Sánchez, J., Unger, L., Dössel, O., Jadidi, A., & Loewe, A. 2023. "AugmentA: Patient-specific Augmented Atrial model Generation Tool". Computerized Medical Imaging and Graphics, 108, 102265. 
</div>

<div class="hanging-indent csl-entry">
Bump, Joseph K; Beyer, Dean; O'Neil, Shawn. 2019. "code, data, and metadata document for the manuscript: Territorial landscapes: incorporating density-dependence into wolf resource selection study designs". Retrieved from the Data Repository for the University of Minnesota, [http://hdl.handle.net/11299/201859](http://hdl.handle.net/11299/201859).
</div>

<div class="hanging-indent csl-entry">
Do, H. X., Smith, J. P., Fry, L. M., Gronewold, A. D. 2020. "Monthly water balance estimates for the Laurentian Great Lakes from 1950 to 2019 (v1.1)" [Data set], University of Michigan - Deep Blue Data. DOI: [https://doi.org/10.7302/tx97-nn12](https://doi.org/10.7302/tx97-nn12)
</div>

<div class="hanging-indent csl-entry">
Heuschele, Deborah; Furuta, Daniel; Smith, Kevin; Marchetto, Peter. 2022. Data and analysis code for "Capturing High Resolution Plant Movement in the Field". Retrieved from the Data Repository for the University of Minnesota (DRUM), DOI: [https://doi.org/10.13020/7e6x-8f36](https://doi.org/10.13020/7e6x-8f36).
</div>

<div class="hanging-indent csl-entry">
Jarai, A., Sun, M. 2022. "Simulation data for toppling and height probabilities in sandpiles. Bath: University of Bath Research Data Archive". DOI: [https://doi.org/10.15125/BATH-01088](https://doi.org/10.15125/BATH-01088). 
</div>

<div class="hanging-indent csl-entry">
Lu, Z., & Ku, Y. 2020. "NeuroRA: A Python toolbox of representational analysis from multi-modal neural data. Frontiers in Neuroinformatics". 14:563669. DOI: [https://doi.org/10.3389/fninf.2020.563669](https://doi.org/10.3389/fninf.2020.563669)
</div>

<div class="hanging-indent csl-entry">
Matúš Medo, Charlotte K. Y. Ng, Michaela Medová. 2024. "A comprehensive comparison of tools for fitting mutational signatures". Nature Communications 15, 9467. URL: [https://www.nature.com/articles/s41467-024-53711-6](https://www.nature.com/articles/s41467-024-53711-6)
</div>

<div class="hanging-indent csl-entry">
Horna Munoz, Daniel; Constantinescu, George; Rhoads, Bruce ; Lewis, Quinn; Sukhodolov, Alexander. 2020. "Confluence Density Effects Simulation Database. University of Illinois at Urbana-Champaign". DOI: [https://doi.org/10.13012/B2IDB-6257171_V1](https://doi.org/10.13012/B2IDB-6257171_V1)
</div>

<div class="hanging-indent csl-entry">
Yang, Huang; Waugh, Darryn W. 2019. "Data associated with Yang et al. 2019. "Dependence of Atmospheric Transport into the Arctic on Extent of the Hadley Cell", Johns Hopkins University Data Archive. DOI: [https://doi.org/10.7281/T1/AWJUGZ](https://doi.org/10.7281/T1/AWJUGZ)
</div>

### Other Resources
::: {#refs}
:::
